### ISSUE TITLE
Ensure compatibility with Yamuna protocol

### ISSUE THREAD

**Issue by aiman** [autonity/aut#155]
The Autonity Yamuna upgrade brings some new protocol features, we should ensure it doesn't break existing commands and we should also aim to support any new features.

**Comment by aiman** [comment]
@cmjc or @yazzaoui can advise on breaking changes and/or what commit to use as a baseline

**Comment by cmjc** [comment]
@aiman - suggest using this tag commit - https://github.com/autonity/autonity/releases/tag/v0.14.0-pre

For breaking changes, I have found the beneath.  @yazzaoui please advise if I have missed anything, TIA.

---

# aut breaking changes.

**Calls broken as ABI changed** (https://github.com/autonity/autonity/compare/v0.13.0...v0.14.0-pre): 

- Contracts changed: Oracle.sol, Accountability.sol, Autonity.sol, Liquid.sol, ACU.sol, Stabilization.sol
- Interfaces changed: IAccountability.sol, IAutonity.sol, IOracle.sol

Examples:

-  `aut contract call --address 0x47e9Fbef8C83A1714F1951F142132E6e90F5fa5D --abi Oracle.abi getRoundData 1809 "SEK-USD"`
`web3.exceptions.ContractPanicError: Panic error 0x32: Array index is out of bounds.`
- `aut protocol config` - returns values in incorrect fields (because new config fields have been added in v0.14.0).


Note also, new for v0.14.0 (vesting, inflation, impact on liquid ntn rewards):

- New contracts :  InflationController.sol, ReentrancyGuard.sol, NonStakableVesting.sol, StakableVesting.sol, ContractBase.sol, LiquidRewardManager.sol
- New Interfaces: IStakeProxy.sol (imported into Liquid.sol), IInflationController.sol, INonStakableVestingVault.sol.


**Calls broken due to BLS aggregation**

Breaks `aut` because:

- in the block header `committedSeals` is renamed to `quorumCertificate`
- the format of the data is different: a single aggregated BLS signature instead of a list of ECDSA signatures is returned.

**New functions for existing command line groups**

- `aut validator` command group  - update to add new interface function to `updateEnode` (See `Autonity.sol` L396 for `updateEnode`

**Comment by cmjc** [comment]
Hi @szemate 

`protocol   Commands related to Autonity-specific protocol operations.`. For example:

```
aut protocol total-redistributed
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes, only got 0 bytes.

The above exception was the direct cause of the following exception:

web3.exceptions.BadFunctionCallOutput: Could not decode contract function call to totalRedistributed with return data: b'', output_types: ['uint256']
```

**Comment by szemate** [comment]
`aut protocol total-redistributed` is broken because the contract function has been renamed. I haven't been able to find any command so far that is broken due to BLS aggregation.

**Comment by cmjc** [comment]
> `aut protocol total-redistributed` is broken because the contract function has been renamed. I haven't been able to find any command so far that is broken due to BLS aggregation.

OK, great. Neither have I (`aut block get` returns the `quorumCertificate` fine.)
